### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by bsbhro** [BojanJurca/Getting-started-with-ESP32-LVGL-for-Arduino-with-1.28-Inch-round-Display-with-Touch#1]
Hi, this address dosn't work.
http://pan.jczn1688.com/directlink/1/ESP32%20module/1.28inch_ESP32-2424S012.zip

And this is unreachable: http://jurca.dyn.ts.si/oscilloscope.html

**Comment by BojanJurca** [comment]
Hello. The first link points to some server which I do not control, but it
seems to be working now.

The second link is my ESP32 server. It occasionally drops the connection
due to heavy traffic in recent days.

Please try again and let me know if it still doesn't work.






V pon., 19. feb. 2024, 13:09 je oseba Bernhard S. ***@***.***>
napisala:

**Comment by bsbhro** [comment]
Thank you! Got a link without the part 'directlink'; after that your link worked too :-)
And I understood the link to the oscilloscope now! Great!
